name: Build Docker Images

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]
  pull_request:
    branches: [main]
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize
  merge_group:

jobs:
  docker-build:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          # - app_name: byc-wa-app
          #   dockerfile: ClientAdvisor/App/WebApp.Dockerfile
          #   registry: bycwacontainerreg.azurecr.io
          #   username: bycwacontainerreg

          - app_name: byoaia-app
            dockerfile: ResearchAssistant/App/WebApp.Dockerfile
            registry: resasscontainerreg.azurecr.io
            username: resasscontainerreg

    uses: ./.github/workflows/build-docker.yml
    with:
      registry: ${{ matrix.registry }}
      username: ${{ matrix.username }}
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' }}
    secrets: inherit
